version: "3.8"
services:
  app:
    container_name: app
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    container_name: web
    image: nginx:1.19.5-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  node:
    container_name: node
    build: ./infra/node
    ports:
      - 5173:5173
    tty: true
    volumes:
      - ./backend:/work
    working_dir: /work

  db:
    container_name: db
    platform: linux/x86_64
    build: ./infra/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 33060:3306
    volumes:
      - db-store:/var/lib/mysql

  db-testing:
    container_name: db-test
    build: ./infra/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 33061:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db

  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    ports:
      - ${WEB_PORT}:4040
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_PROTOCOL: http
      NGROK_PORT: web:80
      # SSLの場合
      # NGROK_PROTOCOL: https
      # NGROK_PORT: web:443

  schemaspy:
    container_name: schemaspy
    build: ./infra/schemaspy
    image: schemaspy/schemaspy
    volumes:
      - ./infra/schemaspy/output:/output
      - ./infra/schemaspy/drivers:/drivers
    command: >
      java -jar schemaspy.jar
      -t mysql
      -dp /drivers
      -host db
      -port 3306
      -db ${DB_NAME}
      -u ${DB_USER}
      -p ${DB_PASS}
      -s ${DB_NAME}
      -o /output
      -connprops allowPublicKeyRetrieval\\=false useSSL\\=false
    depends_on:
      - db

  nginx_schemaspy:
    container_name: nginx_schemaspy
    image: nginx:1.19.5-alpine
    volumes:
      - ./infra/schemaspy/output:/usr/share/nginx/html
    ports:
      - ${NGINX_SCHEMASPY_PORT:-8081}:80

volumes:
  db-store:
